package br.com.staroski.games.spacearena.server.corba;


/**
* br/com/staroski/games/spacearena/server/corba/EnergyItemProviderOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./br/com/staroski/games/spacearena/server/corba/interfaces.idl
* Terça-feira, 3 de Dezembro de 2013 19h26min51s BRST
*/

public interface EnergyItemProviderOperations 
{
  void createNewItem ();
  long getId ();
  int getEnergy ();
} // interface EnergyItemProviderOperations
