package br.com.staroski.games.spacearena.server.corba;


/**
* br/com/staroski/games/spacearena/server/corba/EnergyItemProviderPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./br/com/staroski/games/spacearena/server/corba/interfaces.idl
* Terça-feira, 3 de Dezembro de 2013 19h26min51s BRST
*/

public abstract class EnergyItemProviderPOA extends org.omg.PortableServer.Servant
 implements br.com.staroski.games.spacearena.server.corba.EnergyItemProviderOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("createNewItem", new java.lang.Integer (0));
    _methods.put ("getId", new java.lang.Integer (1));
    _methods.put ("getEnergy", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // br/com/staroski/games/spacearena/server/corba/EnergyItemProvider/createNewItem
       {
         this.createNewItem ();
         out = $rh.createReply();
         break;
       }

       case 1:  // br/com/staroski/games/spacearena/server/corba/EnergyItemProvider/getId
       {
         long $result = (long)0;
         $result = this.getId ();
         out = $rh.createReply();
         out.write_longlong ($result);
         break;
       }

       case 2:  // br/com/staroski/games/spacearena/server/corba/EnergyItemProvider/getEnergy
       {
         int $result = (int)0;
         $result = this.getEnergy ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:br/com/staroski/games/spacearena/server/corba/EnergyItemProvider:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public EnergyItemProvider _this() 
  {
    return EnergyItemProviderHelper.narrow(
    super._this_object());
  }

  public EnergyItemProvider _this(org.omg.CORBA.ORB orb) 
  {
    return EnergyItemProviderHelper.narrow(
    super._this_object(orb));
  }


} // class EnergyItemProviderPOA
