package br.com.staroski.games.spacearena.server.corba;

import br.com.staroski.games.*;

/**
* br/com/staroski/games/spacearena/server/corba/EnergyItemProvider.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./br/com/staroski/games/spacearena/server/corba/interfaces.idl
* Terça-feira, 3 de Dezembro de 2013 19h26min51s BRST
*/

public interface EnergyItemProvider extends EnergyItemProviderOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
	
	public static final String[] INIT_PARAMS = new String[] { "-ORBInitialHost", ObjectBinder.getLocalHost() };

	public static final String ROOT_POA = "RootPOA";

	public static final String SERVICE_NAME = "NameService";

	public static final String LOOKUP_NAME = EnergyItemProvider.class.getSimpleName();
	
} // interface EnergyItemProvider
