package br.com.staroski.games.spacearena.server.corba;


/**
* br/com/staroski/games/spacearena/server/corba/EnergyItemProviderHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./br/com/staroski/games/spacearena/server/corba/interfaces.idl
* Terça-feira, 3 de Dezembro de 2013 19h26min51s BRST
*/

abstract public class EnergyItemProviderHelper
{
  private static String  _id = "IDL:br/com/staroski/games/spacearena/server/corba/EnergyItemProvider:1.0";

  public static void insert (org.omg.CORBA.Any a, br.com.staroski.games.spacearena.server.corba.EnergyItemProvider that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static br.com.staroski.games.spacearena.server.corba.EnergyItemProvider extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (br.com.staroski.games.spacearena.server.corba.EnergyItemProviderHelper.id (), "EnergyItemProvider");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static br.com.staroski.games.spacearena.server.corba.EnergyItemProvider read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_EnergyItemProviderStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, br.com.staroski.games.spacearena.server.corba.EnergyItemProvider value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static br.com.staroski.games.spacearena.server.corba.EnergyItemProvider narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof br.com.staroski.games.spacearena.server.corba.EnergyItemProvider)
      return (br.com.staroski.games.spacearena.server.corba.EnergyItemProvider)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      br.com.staroski.games.spacearena.server.corba._EnergyItemProviderStub stub = new br.com.staroski.games.spacearena.server.corba._EnergyItemProviderStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static br.com.staroski.games.spacearena.server.corba.EnergyItemProvider unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof br.com.staroski.games.spacearena.server.corba.EnergyItemProvider)
      return (br.com.staroski.games.spacearena.server.corba.EnergyItemProvider)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      br.com.staroski.games.spacearena.server.corba._EnergyItemProviderStub stub = new br.com.staroski.games.spacearena.server.corba._EnergyItemProviderStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
